### ISSUE TITLE
Newtonsoft

### ISSUE THREAD

**Issue by DavidWilliams126** [fekberg/applying-asynchronous-programming-c-sharp#1]
Good Morning, 

I'm a little bit of a newb as it relates to C# programming (working on my second college course on C#).  I am having problems on using these files.  I have downloaded the zip.  I copied it into C:\Code\PluralSight then extracted it.  At first it was in a different directory and read some post about insuring the path isn't too long as that can cause problems.  also when unzipping files that can cause my problem.  Below is a screen shot of errors i'm getting when trying to run practice exercises.  I did "restore Nuget" and rebuilt.  

![Screenshot 2021-02-02 070430](https://user-images.githubusercontent.com/77896008/106597833-f6df7600-6524-11eb-9a20-265655c29a26.png)

**Comment by fekberg** [comment]
Hi @DavidWilliams126,

Did you download the code today? That error shouldn't be happening.

If you right click on StockAnalyzer.Core and choose "Rebuild" does that work?

Can you please open StockAnalyzer.Core.csproj and make sure it looks like this:

![image](https://user-images.githubusercontent.com/1154001/106603841-21e6bb80-655f-11eb-9a73-98034450e400.png)

Also make sure you Restore the NuGet packages by right clicking the solution:

![image](https://user-images.githubusercontent.com/1154001/106603939-3dea5d00-655f-11eb-9d2f-20837cf47ac5.png)

I am happy to help!

**Comment by DavidWilliams126** [comment]
Thank you for the quick response.  I did the rebuild and got those errors .

I will look at code after work.

 I downloaded the zip from Pluralsight not GitHub.

Thanks again!  Have a good one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fekberg** [comment]
@DavidWilliams126 No problem!

Download the coder from Github instead, I've made a small change to the project file as Newtonsoft was missing. Will get this uploaded to Pluralsight as soon as possible.

Let me know if you run into more issues!

**Comment by DavidWilliams126** [comment]
Itemgroup for newton.json wasn't in the code.  I added it and it compiled fine.  Thank you.
